## TensorFlow 1.X




### Install TensorFlow 1.X



In [13]:
!pip uninstall -y tensorflow 

Uninstalling tensorflow-2.2.0:
  Successfully uninstalled tensorflow-2.2.0


In [14]:
!pip install tensorflow-gpu==1.15

     |████████████████████████████████| 411.5MB 34kB/s 
     |████████████████████████████████| 3.8MB 42.5MB/s 
     |████████████████████████████████| 512kB 44.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=bb5392137132ea3662f30b0796bb32768d2dfe7bda01b7074a412aa8e778a0ab
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.10.0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3


In [0]:
import tensorflow as tf

In [0]:
tf.__version__

'1.15.0'

### Constants

#### Defining a constant

In [0]:
# Defining a constant using tf
tensor = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [0]:
# If a session were not initializated we cannot access tensor values
tensor.eval()

ValueError: ignored

#### Acessing variables values

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_value = session.run(tensor)

In [0]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Defining a variable

In [0]:
# Defining a variable on TensorFlow
variable = tf.Variable([[30, 20], [10, 45]])

In [0]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [0]:
# If a session were not iniatilizated we cannot access the variable values
variable.eval()

ValueError: ignored

#### Acessando os valores de uma variável

In [0]:
# Inicialize a session
session = tf.Session()

In [0]:
# Inicializing all variables in a session
session.run(tf.global_variables_initializer())

In [0]:
# Exectuing a module to acess all values
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Install TensorFlow 2.0

In [0]:
!pip install tensorflow-gpu==2.0.0

     |████████████████████████████████| 380.8MB 43kB/s 
     |████████████████████████████████| 450kB 46.5MB/s 
     |████████████████████████████████| 3.8MB 42.6MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-gpu 1.15.0
    Uninstalling tensorflow-gpu-1.15.0:
      Successfully uninstalled tensorflow-gpu-1.15.0


In [0]:
import tensorflow as tf
import numpy as np

In [0]:
tf.__version__

'2.2.0'

### Constants

#### Defining a constant

In [0]:
# Defining a constant on TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [0]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
# Acessin Tensor Dimensions
tensor_20.shape

TensorShape([2, 2])

#### Acessing constants values

In [0]:
# Use numpy without inicialize a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# Convert an array to Tensor
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [0]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Defining a variable

In [0]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessing values of a variable

In [0]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing a value in a variable

In [0]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Math operations with tensor

In [0]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Scalar sum


In [0]:
tensor + 2

<tf.Tensor: id=22, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiply a escalar by a tensor

In [0]:
tensor * 5

<tf.Tensor: id=24, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

### Using tensorflow native functions

In [0]:
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [0]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
#Add
tf.add (tensor,tensor_20)

<tf.Tensor: id=45, shape=(2, 2), dtype=int32, numpy=
array([[24,  6],
       [35, 55]], dtype=int32)>

In [0]:
#Subtract
tf.subtract (tensor, tensor_20)

<tf.Tensor: id=46, shape=(2, 2), dtype=int32, numpy=
array([[-22,  -2],
       [-29, -47]], dtype=int32)>

In [0]:
# Multiply
tf.multiply(tensor,tensor_20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 529,   16],
       [1024, 2601]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

In [0]:
# Squaring
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [0]:
# Squareroot
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [0]:
#Add
np.add(tensor, tensor_20)

array([[24,  6],
       [35, 55]], dtype=int32)

In [0]:
#Subtract
np.subtract(tensor, tensor_20)

array([[-22,  -2],
       [-29, -47]], dtype=int32)

In [0]:
#Division
np.divide(tensor, tensor_20)

array([[0.04347826, 0.5       ],
       [0.09375   , 0.07843137]])

In [0]:
#Multiply
np.multiply(tensor, tensor_20)

array([[ 23,   8],
       [ 96, 204]], dtype=int32)

#### Dot product 

In [0]:
tensor

<tf.Tensor: id=20, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [0]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [0]:
tf.add (tensor,tensor_20)

<tf.Tensor: id=25, shape=(2, 2), dtype=int32, numpy=
array([[24,  6],
       [35, 55]], dtype=int32)>

### Strings on TensorFlow 2.0

In [0]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operating with strings

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [0]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Storing arrays (vector) of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [0]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
